**1. (12 points)** This question is about the matrix
$$A = \begin{bmatrix}
            1 & 2 & 0 & 1 \\ 
            2 & 4 & 1 & 4 \\
            3 & 6 & 3 & 9
      \end{bmatrix}$$
      
**(a)** Find a lower triangular $L$ and an upper triangular $U$ so that $A = LU$.

In [1]:
import sympy as sp
import numpy as np


A = sp.Matrix([
    [1, 2, 0, 1],
    [2, 4, 1, 4],
    [3, 6, 3, 9]
])

L, U, P = A.LUdecomposition()
L

Matrix([
[1, 0, 0],
[2, 1, 0],
[3, 3, 1]])

In [2]:
U

Matrix([
[1, 2, 0, 1],
[0, 0, 1, 2],
[0, 0, 0, 0]])

In [3]:
A == L * U

True

**(b)** Find the reduced row echelon form $R = rref(A)$. How many independent columns in $A$?

In [4]:
A.rref()[0]

Matrix([
[1, 2, 0, 1],
[0, 0, 1, 2],
[0, 0, 0, 0]])

There are two independent columns in $A$.

**(c)** Find a basis for the nullspace of A.

In [5]:
A.nullspace()[0]

Matrix([
[-2],
[ 1],
[ 0],
[ 0]])

In [6]:
A.nullspace()[1]

Matrix([
[-1],
[ 0],
[-2],
[ 1]])

**(d)** If the vector $b$ is the sum of the four columns of $A$, write down the complete solution to
$Ax = b$.

In [7]:
x_particular = sp.Matrix([
    [1],
    [1],
    [1],
    [1]
])

b = A * x_particular

b

Matrix([
[ 4],
[11],
[21]])

$x = \begin{bmatrix}
          1 \\
          1 \\
          1 \\
          1
     \end{bmatrix}$$
     + c1
     \begin{bmatrix}
          -2 \\
          1  \\
          0  \\
          0
     \end{bmatrix}
     +$ $c2
     \begin{bmatrix}
          -1 \\
          0  \\
          -2 \\
          1
     \end{bmatrix}$
     

**2. (11 points)** This problem finds the curve $y = C + D 2^t$ which gives the best least squares fit
to the points $(t, y) = (0, 6),(1, 4),(2, 0)$.

**(a)** Write down the $3$ equations that would be satisfied if the curve went through all $3$ points.

Just substitute the points:<br>
$C + D2^0 = C + D = 6$<br>
$C + D2^1 = C + 2D = 4$<br>
$C + D2^2 = C + 4D = 0$<br>

**(b)** Find the coefficients $C$ and $D$ of the best curve $y = C + D2^t$

Using the normal equations:

In [8]:
A = sp.Matrix([
    [1, 1],
    [1, 2],
    [1, 4]
])

y = sp.Matrix([
    [6],
    [4],
    [0]
])

best_theta = (A.T * A).inv() * A.T * y
best_theta

Matrix([
[ 8],
[-2]])

Using the pseudoinverse:

In [9]:
A.pinv() * y

Matrix([
[ 8],
[-2]])

**(c)** What values should $y$ have at times $t = 0, 1, 2$ so that the best curve is $y = 0$?

The question is asking about the vector y that projected onto the zero vector. (it asking about the ***nullspace*** of $P$)<br>
The projection matrix $P$:

In [10]:
P = (A.T * A).inv() * A.T
P

Matrix([
[   1,   1/2, -1/2],
[-2/7, -1/14, 5/14]])

In [11]:
P.nullspace()[0]

Matrix([
[ 2],
[-3],
[ 1]])

and all linear combination of this line:

$c \begin{bmatrix} 2 \\ -3 \\ 1 \end{bmatrix}$

**3. (11 points)** Suppose $Av_i = b_i$ for the vectors $v_1,..., v_n$ and $b_1,..., b_n$ in $R^n$. Put the $v$’s into
the columns of $V$ and put the $b$’s into the columns of $B$.

**(a)** Write those equations $Av_i = b_i$ in matrix form. What condition on which vectors allows $A$
to be determined uniquely? Assuming this condition, find $A$ from $V$ and $B$.

$A = B V^{-1}$<br>
Matrix $V$ should be ***invertable*** matrix.

**(b)** Describe the column space of that matrix $A$ in terms of the given vectors.

The vectors of the columns of matrix $B$ ***spans*** the columnspace of the matrix $A$, $C(A)$.

**(c)** What additional condition on which vectors makes $A$ an invertible matrix? Assuming this,
find $A^{−1}$ from $V$ and $B$.

Matrix $B$ should be ***invertable*** matrix.<br>
$A^{-1} = V B^{-1}$<br>

**4. (11 points)**

**(a)** Suppose $x_k$ is the fraction of MIT students who prefer calculus to linear algebra at year $k$.
The remaining fraction $y_k = 1 − x_k$ prefers linear algebra

At year $k + 1$, $1/5$ of those who prefer calculus change their mind (possibly after taking
18.03). Also at year $k + 1$, $1/10$ of those who prefer linear algebra change their mind
(possibly because of this exam).

Create the matrix $A$ to give $\begin{bmatrix} x_{k+1} \\ y_{k+1} \end{bmatrix} = A \begin{bmatrix} x_{k} \\ y_{k} \end{bmatrix}$ and find the limit of $A^k \begin{bmatrix} 1 \\ 0 \end{bmatrix}$ as $k \to \infty$.

Matrix $A$ would be:<br>
$A = \begin{bmatrix} 
        1 - 1/5 & 1/10 \\ 
        1/5 & 1 - 1/10
     \end{bmatrix}
$

In [12]:
xk, yk = sp.symbols('xk yk')

x = sp.Matrix([
    [xk],
    [yk]
])

A = sp.Matrix([
    [1 - 1/5, 1/10],
    [1/5, 1 - 1/10]
])

A * x

Matrix([
[0.8*xk + 0.1*yk],
[0.2*xk + 0.9*yk]])

$A^k \begin{bmatrix} 1 \\ 0 \end{bmatrix}$ as $k \to \infty$:<br>
$c_1 \lambda^k_1x_1$

In [13]:
x1 = A.eigenvects()[1][-1][0]
x1

Matrix([
[0.471404520791032],
[0.942809041582063]])

In [14]:
c = sp.Matrix.hstack(A.eigenvects()[1][-1][0], A.eigenvects()[0][-1][0]).inv() * sp.Matrix([
    [1],
    [0]
])
c

Matrix([
[0.707106781186548],
[0.942809041582063]])

$A^k \begin{bmatrix} 1 \\ 0 \end{bmatrix}$ as $k \to \infty$:

In [15]:
c[0] * x1

Matrix([
[0.333333333333333],
[0.666666666666667]])

**(b)** Solve these differential equations, starting from $x(0) = 1, y(0) = 0$ :<br>
$dx/dy = 3x − 4y \quad dy/dt= 2x − 3y$.

In [16]:
u0 = sp.Matrix([
    [1],
    [0]
])

A = sp.Matrix([
    [3, -4],
    [2, -3]
])

A

Matrix([
[3, -4],
[2, -3]])

In [17]:
A.eigenvects()

[(-1,
  1,
  [Matrix([
   [1],
   [1]])]),
 (1,
  1,
  [Matrix([
   [2],
   [1]])])]

In [18]:
x1 = A.eigenvects()[0][-1][0]
x2 = A.eigenvects()[1][-1][0]

lambda1 = A.eigenvects()[0][0]
lambda2 = A.eigenvects()[1][0]

c = sp.Matrix.hstack(x1, x2).inv() * u0
c

Matrix([
[-1],
[ 1]])

$u(t) = e^{t} \begin{bmatrix}2 \\ 1 \end{bmatrix} - e^{-t} \begin{bmatrix}1 \\ 1 \end{bmatrix}$

**(c)** For what initial conditions $\begin{bmatrix} x(0) \\ y(0) \end{bmatrix}$ does the solution to this differential equation
$\begin{bmatrix} x(t) \\ y(t) \end{bmatrix}$
lie on a single straight line in R2 for all $t$?

When the starting point $\begin{bmatrix} x(0) \\ y(0) \end{bmatrix}$ lies along one of the eigenvectors.

**5. (11 points)**

**(a)** Consider a $120^\circ$ rotation around the axis $x = y = z$. Show that the vector $i = (1, 0, 0)$ is
rotated to the vector $j = (0, 1, 0)$. (Similarly $j$ is rotated to $k = (0, 0, 1)$ and $k$ is rotated to
$i$.) How is $j − i$ related to the vector $(1, 1, 1)$ along the axis?

$j - i$ is the projection vector $e$ onto this axis $(1, 1, 1)$ which is perpendicular to it:

In [19]:
i = sp.Matrix([
    [1],
    [0],
    [0]
])

j = sp.Matrix([
    [0],
    [1],
    [0]
])

axis = sp.Matrix([
    [1],
    [1],
    [1]
])

e = j - i
e

Matrix([
[-1],
[ 1],
[ 0]])

**(b)** Find the matrix $A$ that produces this rotation (so $Av$ is the rotation of $v$). Explain why
$A^3 = I$. What are the eigenvalues of $A$?

To find matrix $A$, write $$T(v_{i}) = \sum_{i}\sum_{j} a_{ji}v_i, 1 \leq i, j \leq 3$$ Then A:

In [20]:
A = sp.Matrix([
    [0, 0, 1],
    [1, 0, 0],
    [0, 1, 0]
])

A

Matrix([
[0, 0, 1],
[1, 0, 0],
[0, 1, 0]])

Why $A^3$ coz we rotate other $360^\circ$ ($120 * 3$):

In [21]:
A ** 3

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

**(c)** If a $3$ by $3$ matrix $P$ projects every vector onto the plane $x+2y+z = 0$, find three eigenvalues
and three independent eigenvectors of $P$. No need to compute $P$.

Any projection matrix $P$ has two eigenvalues, $0$ or $1$, for any orthognal vector on the space, and any vector in the space. The eigenvectors corresponding to these eigenvalues are $(-1, 1, -1), (1, 2, 1)$ and we can choose any third eigenvector not in the same direction of the previous ones.


$6$. **(11 points)** This problem is about the matrix:
$$A = \begin{bmatrix} 1 & 2 \\ 2 & 4 \\ 3 & 6 \end{bmatrix}$$

**(a)** Find the eigenvalues of $A^T A$ and also of $AA^T$. For both matrices find a complete set of
orthonormal eigenvectors.

The eigenvalues of $A^T$ and $AA^T$ are equivalent to each others, which can be found using **SVD**:

In [22]:
A = np.array([
    [1, 2],
    [2, 4],
    [3, 6]
])

U, S, V = np.linalg.svd(A)
S # eigenvalues of A^TA and AA^T

array([8.36660027e+00, 7.32018325e-16])

Complete set of orthogonal eigenvectors:

In [23]:
U

array([[-0.26726124,  0.94816592,  0.17190932],
       [-0.53452248,  0.00256504, -0.84515036],
       [-0.80178373, -0.31776533,  0.50613047]])

In [24]:
V

array([[-0.4472136 , -0.89442719],
       [-0.89442719,  0.4472136 ]])

**(b)** If you apply the Gram-Schmidt process (orthonormalization) to the columns of this matrix
A, what is the resulting output?

We can normalize one of the columns, but we can not project them on each other since they are in the same direction:

In [25]:
A = sp.Matrix(A)
A[:, 0].normalized()

Matrix([
[  sqrt(14)/14],
[   sqrt(14)/7],
[3*sqrt(14)/14]])

**(c)** If $A$ is any $m$ by $n$ matrix with $m > n$, tell me why $AA^T$ cannot be positive definite. Is
$A^T A$ always positive definite? (If not, what is the test on $A$?)

$A A^T$ can not be positive definite since it will a singular matrix. Any matrix A with $m > n$ has a non trivial vector $x$ such that $Ax = 0$.

$A^T A$ always positive definite when $A$ is invertable and for any non zero vector $x$, $x^T (A^T A) x > 0$.

**7. (11 points)** This problem is to find the determinants of
$$A = 
\begin{bmatrix} 
1 & 1 & 1 & 1 \\
1 & 1 & 1 & 1 \\
1 & 1 & 1 & 0 \\
1 & 1 & 0 & 0 
\end{bmatrix} \quad
B = 
\begin{bmatrix} 
0 & 1 & 1 & 1 \\
1 & 1 & 1 & 1 \\
1 & 1 & 1 & 0 \\
1 & 1 & 0 & 0 
\end{bmatrix} \quad
C = 
\begin{bmatrix} 
x & 1 & 1 & 1 \\
1 & 1 & 1 & 1 \\
1 & 1 & 1 & 0 \\
1 & 1 & 0 & 0 
\end{bmatrix} \quad
$$

**(a)** Find det $A$ and give a reason.

det($A$) is zero, since it has a repeated columns (first and second columns).

In [26]:
A = sp.Matrix([
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 0],
    [1, 1, 0, 0],
])

A.det()

0

**(b)** Find the cofactor $C_{11}$ and then find det $B$. This is the volume of what region in R4?

In [27]:
C11 = A[1:, 1:]
C11.det()

-1

In [28]:
B = sp.Matrix([
    [0, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 0],
    [1, 1, 0, 0],
])

B.det()

1

Det of $B$ is equal to the volume of the box with edges of rows of $B$ in $\mathbb{R}^4$

det ($C$) $=$ $xC_{11}$ + det ($B$) $= −x + 1$.

**8. (11 points)**

**(a)** When $A$ is similar to $B = M^{−1}AM$, prove this statement:
If $A^k \rightarrow 0$ when $k \rightarrow
\infty$, then also $B^k \rightarrow 0$.

When matrix $A$ is similar to matrix $B$, then both of matrices shre the same eigenvalues $\Lambda$ matrix.

$B = S \Lambda S^{-1}$. $A^k \rightarrow 0$ when $k \rightarrow
\infty$ iff real part of $|\lambda_{i}|$ < 1, hence $B^k \rightarrow 0$ when $k \rightarrow
\infty$.

**(b)** Suppose $S$ is a fixed invertible $3$ by $3$ matrix.<br>
This question is about all the matrices $A$ that are diagonalized by $S$, so that
$S^{−1}AS$ is diagonal. Show that these matrices $A$ form a subspace of
$3$ by $3$ matrix space. (Test the requirements for a subspace.)

They form a subspace, since $S^{-1}(c_1A + c_2 B)S$ is also a diagonal matrix.

**(c)** Give a basis for the space of $3$ by $3$ diagonal matrices. Find a basis for the space in part (b)
— all the matrices $A$ that are diagonalized by $S$.

$$
\begin{bmatrix}
1 & 0 & 0 \\
0 & 0 & 0 \\
0 & 0 & 0 \\
\end{bmatrix} \quad, 
\begin{bmatrix}
0 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 0 \\
\end{bmatrix} \quad, 
\begin{bmatrix}
0 & 0 & 0 \\
0 & 0 & 0 \\
0 & 0 & 1 \\
\end{bmatrix}
$$